name: test and build
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run tests
      run: |
        go test -cover github.com/oligoden/meta/entity
        go test -cover github.com/oligoden/meta/entity/state
        go test -cover github.com/oligoden/meta/refmap

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Build
      run: |
        export GO111MODULE=on
        GOOS=windows GOARCH=amd64 go build -o bin/meta-windows-amd64.exe
        GOOS=linux   GOARCH=amd64 go build -o bin/meta-linux-amd64
    - name: upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: binaries
        path: bin/